# Generated by Django 4.2.1 on 2023-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
