# Generated by Django 4.2.1 on 2023-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0003_remove_abouttranslation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='header',
            field=models.CharField(default='', max_length=255),
        ),
    ]
