# Generated by Django 4.2.1 on 2023-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0005_product_shortdescription_deliverytranslation_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
