# Generated by Django 4.2.1 on 2023-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_content', '0005_requisites_requisitestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitestranslation',
            name='address',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='requisitestranslation',
            name='bank',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='requisitestranslation',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitestranslation',
            name='fax',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitestranslation',
            name='rs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitestranslation',
            name='unn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
